
OBS_DATA_DIR = "/Users/Julie/Desktop/wfrt_msc-thesis/data/eccc_data"
PRED_DATA_DIR = "/Users/Julie/Desktop/wfrt_msc-thesis/data/prediction_data"

# DOMAIN BOUNDS
DOMAIN_MINX = -126.77383
DOMAIN_MINY = 43.16403
DOMAIN_MAXX = -124.925285
DOMAIN_MAXY = 66.57196

# REQUESTED FIELD
UNIVERSAL_FIELDS = "ID%2CSTN_ID%2CUTC_DATE%2C"
VERIF_FIELDS = f"{UNIVERSAL_FIELDS}TEMP%2CPRECIP_AMOUNT%2CWIND_SPEED%2CWIND_DIRECTION"
VISIBILITY_FIELDS = f"{UNIVERSAL_FIELDS}TEMP%2CDEW_POINT_TEMP%2CPRECIP_AMOUNT%2CRELATIVE_HUMIDITY%2CVISIBILITY"

